
# AIS e-learning course #3 on economic indicators using AIS
Central Statisics Office - Ireland<br>
Transport Section<br>
August 2024<br>
Nele van der Wielen Nele.vanderWielen@cso.ie<br>
Justin McGurk Justin.McGurk@cso.ie<br>
## AIS Course Part 2
### Test and demonstration of Process
### ***S***tationary ***M***arine ***B***roadcast (SMB)

This work book uses a single ship for a year in global scope<br>
This notebook will generate data of stopped ship<br>
and is the source of data for<br>
* _OutputResults\AIS_Course_Global_SingleShip\Global_H3_int_index_10_k_3_period_20220101_to_20221231.csv_

### Style notes
Will always prefix pandas object with pd_ to make it clear what type of<br>
dataframe object we are dealing with.<br>
<br>
Likewise geopandas with gpd_.<br>
<br>
The default is spark so when we have pandas or geopandas data frame be explicit.<br>
* spark --> dataframe_name<br>
* pandas --> pd_dataframe_name<br>
* geopandas --> gpd_dataframe_name<br>

#### For easy reference, every section in this notebook will start with a number.

### Contents
* 0 - Initial set up
* 1 - Set parameters
* 2 - Fetch AIS data
* 3 - Spatial and adding sorting variable. - Spatial component not used as global use case in this example
* 4 - Gets distinct MMSI - Not necessary in this case as single ship
* 5 - Define internal functions and parameters to implement stopped ship
* 6 - Run stopped ship proccess
* 7 - Use stopped ship data
* 8 - Data push out

# 0 - Initial set up
Import requisites necessary for git import and AIS packages.<br>
## Kernel
Choose "ais-tt". This kernel has additional spark configuration.
If you would like to choose other kernel, make sure to add the configuration either
<br>**thru SPOT template:**
```
"spark.sql.parquet.enableVectorizedReader": "false"
```

<br>**thru Jupyter Notebook:**

```
spark.conf.set("spark.sql.parquet.enableVectorizedReader", "false")
```

In [1]:
from pyspark.sql import SparkSession
import pyspark.sql.functions as F

spark = SparkSession.builder.getOrCreate()

#### Now import AIS helper functions and Alias
## AIS package -- install using pip
A project-level read-only token has been generated for use of the AIS Task Team.

#### Note tokens only have a maximum life of one year.<br>
Tokens will expire 2025-07-10

In [2]:
# get our required imports to allow for git import
import sys
import os
import sys
import subprocess

git_lab_tokens = [

    
    ['ml_group_read_only_20250710',
     'Sysu_RFimzcVbz-p1xbT',
     'code.officialstatistics.org/mlpolygonsalgorithm/ml-group-polygons.git'],
    
    ['CSO_Ireland_AIS_functions_read_repo_20250710',
     'SUAMELCRBvuik8MWFgYN', 
     'code.officialstatistics.org/cso-ireland-ais/functions.git'],
    
    ['CSO_AIS_Upload_Data_read_20250710',
     '7VKv26ScZ7wF1v3rn8jj',
     'code.officialstatistics.org/cso-ireland-ais/upload-data.git' ]
]

for g in git_lab_tokens:
    GITLAB_USER = g[0]
    GITLAB_TOKEN = g[1]
    GITLAB_REPO = g[2]
    git_package =  f"git+https://{GITLAB_USER}:{GITLAB_TOKEN}@{GITLAB_REPO}"
    print(" Installing Packages!") # 
    std_out = subprocess.run([sys.executable, "-m", "pip", "install", git_package], capture_output=True, text=True).stdout
    print(std_out) # --- Set to True to debug pip package installation
    print("Done!")

 Installing Packages!
Collecting git+https://ml_group_read_only_20250710:****@code.officialstatistics.org/mlpolygonsalgorithm/ml-group-polygons.git
  Cloning https://ml_group_read_only_20250710:****@code.officialstatistics.org/mlpolygonsalgorithm/ml-group-polygons.git to /tmp/pip-req-build-o4c9mn4z
  Resolved https://ml_group_read_only_20250710:****@code.officialstatistics.org/mlpolygonsalgorithm/ml-group-polygons.git to commit 612cd23bb986ee34b1c467a479a181214d20c06e
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'

Done!
 Installing Packages!
Collecting git+https://CSO_Ireland_AIS_functions_read_repo_20250710:****@code.officialstatistics.org/cso-ireland-ais/functions.git
  Cloning https://CSO_Ireland_AIS_functions_read_repo_20250710:****@code.officialstatistics.org/cso-ireland-ais/functions.git to /tmp/pip-req-build-p_d4b69i
  Resolved https://CSO_Ireland_AIS_functions_read_repo_20250710:****@code.officialstatistics.org/cso-ireland-ais/functions.git to commit 0b17a205e8ba0d8518744c7bae16c48f076baea3
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'

Done!
 Installing Packages!
Collecting git+https://CSO_AIS_Upload_Data_read_20250710:****@code.officialstatistics.org/cso-ireland-ais/upload-data.git
  Cloning https://CSO_AIS_Upload_Data_read_20250710:****@code.officialstatistics.org/cso-ireland-ais/upload-data.git to /tmp/pip-req-build-gpywzdi5
  Resolved https://CSO_AIS_Upload_Data_read_20250710:****@code.officialstatistics.org/cso-ireland-ais/upload-data.git to commit cb1c022334f94aa7a6f0e75c65f9d63c1568390d
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'

Done!

### Now do imports and alias of git sourced functionality

In [3]:
# import ais and give it an alias - af
from ais import functions as af
#Now import cso and give it an alias - cso_load
from upload_data import load as cso_load
from cso_ais import cso_ais as cso_a
from cso_utility import cso_utility as cso_u
from cso_proximity import cso_proximity as cso_p

##### ais - developed by
* Cherryl Chico and AIS TT (ADB)

#####  upload_data - developed by 
* Justin McGurk (Methodologloy)
* Nele van der Wielen (Transport and Tourism) 

##### cso_ais
* Justin McGurk (Methodologloy)
* Nele van der Wielen (Transport and Tourism) 

##### cso_utility
* Justin McGurk (Methodologloy)
* Nele van der Wielen (Transport and Tourism) 

##### cso_proximity
* Justin McGurk (Methodologloy)
* Nele van der Wielen (Transport and Tourism)

In [4]:
### Now do imports and alias of standard python libraries .

In [5]:
#Other librarys
import pandas as pd
import geopandas as gpd
import numpy as np
import requests
import copy


import math # Not used as yet but maybe
import matplotlib.pyplot as plt


from datetime import datetime
from functools import reduce #used at end in data data frame appending

In [6]:
# Clean up 
try:
    del GITLAB_USER, GITLAB_TOKEN, git_package, std_out
except:
    pass

## Imports of boiler plate for Sedona
##### Not 100% sure all this is needed.
It may take a couple of mins to complete

In [7]:
from pyspark.sql import SparkSession
import pyspark.sql.functions as F

spark = SparkSession.builder.getOrCreate()

👆👆👆👆<br>
True?  -- OK GOOD to GO!<br>
# Inititilisation is completed
### Now Ready for do something

We have now installed all our packages we need. How to use the ais functions is outlined<br>
in another document availaible [here](https://code.officialstatistics.org/trade-task-team-phase-1/samplecode/-/blob/master/aisDataExtractionDemo.ipynb)<br>
<br>
We will now focus on introducing the functions developed by the Central Statistics Office Ireland to implement SMB method.<br>
The next few sections will

### SedonaRegistrator Process
The optional GeoTools library is required only if you want to use CRS transformation and ShapefileReader.<br>
https://sedona.apache.org/tutorial/sql-python/<br>
enabling Sedona geometry and index serializers -->  robbed from <br>
https://github.com/apache/incubator-sedona/blob/master/binder/ApacheSedonaSQL.ipynb<br>
https://github.com/apache/incubator-sedona/blob/master/binder/ApacheSedonaCore.ipynb<br>

removed 'org.apache.sedona:sedona-python-adapter-3.0_2.12:1.1.0-incubating,org.datasyslab:geotools-wrapper:1.1.0-25.2'<br>
http://sedona.incubator.apache.org/setup/maven-coordinates/<br>
Indicate is use for OGS is<br>
The optional GeoTools library is required only if you want to use CRS transformation and ShapefileReader. <br>
neither of which we are going to do.<br>
## This process will take a couple of mins
### Returns: true - --> Success.

In [8]:
# Pyspark Imports

# https://sedona.apache.org/tutorial/sql-python//
# enabling Sedona geometry and indes serializers -->  robbed from 
# https://github.com/apache/incubator-sedona/blob/master/binder/ApacheSedonaSQL.ipynb
# https://github.com/apache/incubator-sedona/blob/master/binder/ApacheSedonaCore.ipynb

# removed 'org.apache.sedona:sedona-python-adapter-3.0_2.12:1.1.0-incubating,org.datasyslab:geotools-wrapper:1.1.0-25.2'
# http://sedona.incubator.apache.org/setup/maven-coordinates/
# Indicate is use for OGS is
# The optional GeoTools library is required only if you want to use CRS transformation and ShapefileReader. 
# neither of which we are going to do.

#'''
#spark = SparkSession. \
#    builder. \
#    appName('thatapp'). \
#    config("spark.serializer", KryoSerializer.getName). \
#    config("spark.kryo.registrator", SedonaKryoRegistrator.getName). \
#    config('spark.jars.packages',
#           'org.apache.sedona:sedona-python-adapter-3.0_2.12:1.1.0-incubating,org.datasyslab:geotools-wrapper:1.1.0-25.2'). \
#    getOrCreate()
#'''

👆👆👆👆<br>
True?  -- OK GOOD to GO!<br>
Currently not implemented<br>

# Inititilisation is completed
### Now Ready for Do it!

# 1: Set parameters
In this section we set the parameters and variables that define our search space.
### START - Hyper-Parameters
**start_date** - for ais data used in prcess<br>
**end_date** - for ais data used in process<br>

#### hardcoded
the_k_depth = 3<br>
- how deep is our k-ring<br>

the_h3  = "H3_int_index_10"<br>
- The field name/resolution we are going to use for k-ring building<br>

get_mmsi = [250006549]<br>
- The specific ship we are going to get <br>

the_h3_2_list = [585892912802299903, <br>
                 585890713779044351, <br>
                 585891263534858239, <br>
                 585913803523227647, <br>
                 585893462558113791]<br>
- The five h3 cells we need to fetch from.

columns_ais = [<br>
"mmsi",<br>
"imo",<br>
"vessel_type",<br>
"vessel_type_code", <br>
"vessel_type_main",<br>
"vessel_type_sub",<br>
"length",<br>
"width",<br>
"latitude",<br>
"longitude",<br>
"draught", <br>
"sog", <br>
"cog", <br>
"rot", <br>
"heading", <br>
"nav_status",<br>
"dt_pos_utc",<br>
"dt_insert_utc",<br>
"H3_int_index_2",<br>
"H3_int_index_7",<br>
"H3_int_index_8",<br>
"H3_int_index_9",<br>
"H3_int_index_10",<br>
"H3_int_index_11",<br>
"message_type"<br>
]<br>
- The columns of AIS data we need to fetch.<br>

columns_shipping = [<br>
'LRIMOShipNo',<br>
'MaritimeMobileServiceIdentityMMSINumber',<br>
'ShiptypeLevel5',<br>
'ShipName',<br>
'Tonnagesystem69convention',<br>
'GrossTonnage',<br>
'Deadweight'<br>
]<br>
- The columns of Shipping data we need to fetch.<br>

In [9]:
# Hyper-parameters: control depth of k-ring size and h3 Index used for observation clustering as implemented
# cso_k_ring and cso_h3_adjacency_test.  We need to id which H3 Index data we are using and the depth of the k-ring
# these are definite article, hence the use of the_name

the_k_depth = 3
the_h3  = "H3_int_index_10"
# Get the H3 incies at resolution 2 for our study area (Ireland)




# AIS Time Duration - Test - One day - For demo 24th March 2023
#start_date = datetime.fromisoformat("2023-03-24")
#end_date = datetime.fromisoformat("2023-03-24")

# AIS Time Duration - Test - One Month  - For demo  March 2023
#start_date = datetime.fromisoformat("2023-03-01")
#end_date = datetime.fromisoformat("2023-03-31")

# Partial monty 4 quarters of data 2022
#start_date = datetime.fromisoformat("2022-01-01")
#end_date = datetime.fromisoformat("2022-12-31")

# Partial monty 2 quarters of data 2022
#start_date = datetime.fromisoformat("2022-01-01")
#end_date = datetime.fromisoformat("2022-06-30")
#start_date = datetime.fromisoformat("2022-07-01")
#end_date = datetime.fromisoformat("2022-12-31")

# Static input - Full year for a single ship
start_date = datetime.fromisoformat("2022-01-01")
end_date = datetime.fromisoformat("2022-12-31")
get_mmsi = [250006549]

# Dynamic Input
#start_date = input('Start Date: yyyy-mm-dd')
#end_date= input('End Date: yyyy-mm-dd')
#get_mmsi = [250006549]

In [10]:
#### Variables (Start and end date...)
print(start_date)
print(end_date)

2022-01-01 00:00:00
2022-12-31 00:00:00

In [11]:
# Get the H3 incies at resolution 2 for our study area (Ireland) - this will not be used in this case.
the_h3_2_list = [585892912802299903, 585890713779044351, 585891263534858239, 585913803523227647, 585893462558113791]

columns_ais = [
"mmsi",
"imo",
"vessel_type",
"vessel_type_code", 
"vessel_type_main",
"vessel_type_sub",
"length",
"width",
"latitude",
"longitude",
"draught", 
"sog", 
"cog", 
"rot", 
"heading", 
"nav_status",           
"dt_pos_utc",
"dt_insert_utc",
"H3_int_index_2",
"H3_int_index_7",
"H3_int_index_8",        
"H3_int_index_9",         
"H3_int_index_10",
"H3_int_index_11",
"message_type"
]

columns_shipping = [
'LRIMOShipNo',
'MaritimeMobileServiceIdentityMMSINumber',
'ShiptypeLevel5',
'ShipName',
'Tonnagesystem69convention',
'GrossTonnage',
'Deadweight'
]

# Fields we wish to keep for each type for geometry dataframe stripping
keep_fields_bbb = ['geom']
keep_fields_ports = ['geom', 'port_name', 'port']
keep_fields_ports_attributes = ['port_name', 'port']

# Get some runtime data for debugging can only start once import of datetime has completed
startScript= datetime.now()

#make a string that uses hyper-paramters to create name-will use this at end for name of download csv of results
#output_csv = f'{the_h3}_k_{the_k_depth}_run_{startScript.strftime("%Y%m%d_%H%M")}_period_{start_date.strftime("%Y%m%d")}_to_{end_date.strftime("%Y%m%d")}.csv'
output_csv = f'Global_{the_h3}_k_{the_k_depth}_period_{start_date.strftime("%Y%m%d")}_to_{end_date.strftime("%Y%m%d")}.csv'
print(f'Output file will be named: {output_csv}')

Output file will be named: Global_H3_int_index_10_k_3_period_20220101_to_20221231.csv

### - END - Set parameters

# 2 - Fetch AIS data
create data  using ais function from task team

In [12]:
#af.get_ais?

In [13]:
ais_data= af.get_ais(spark,
                start_date, 
                end_date = end_date,
                #h3_list = the_h3_2_list, # get global data for this ship
                mmsi_list =  get_mmsi,
                columns = columns_ais).cache()

# 3: Spatial Processes on AIS for data reduction
## 3.1 - Spatial – Geometry creation!
For this global case we do not need to do any of this
### Process AIS Data

In [14]:
cso_a.cso_ais2geom?

Signature:
cso_a.cso_ais2geom(
    spark,
    df,
    x_field='longitude',
    y_field='latitude',
    llx=-12.0,
    lly=51.1,
    urx=-5.5,
    ury=55.6,
)
Docstring:
Creates spatial object from AIS data that allows for down stream spatial processing.
Have a data frame of AIS data from UN Global platform, does filter on 'Irish Box' with
default parameters supplied for Irish Context.
Returns a data frame with point spatial object: geom.

Parameters
----------
spark: SparkSession

df: spark data frame:
    out put from ais.get_ais() function.

x_field: string: (default- 'longitude')
    field in df that correspoinds to longitude value

y_field: string: (default- 'latitude')
    field in df that correspoinds to latitude value

llx: float: (default -12.0)
    Lower left long

lly: float: (default 51.1)
    Lower left lat

urx: float: (default -5.5)
    Upper Right long

ury: float: (default 55.6)
    Upper Right lat

Returns
----------
spark data frame with point spatial object added: geom
File:      /opt/python/lib/python3.11/site-packages/cso_ais/_ais.py
Type:      function

In [15]:
# we don't need to create geometry or anything of this nature.
# Now need to add unix time for our data still as we need this to ensure sorting
# in the correct temporal order.
ais_data = cso_a.cso_ais2unixtime(spark,ais_data)

# 4: Get list of distinct AIS MMSI 
####  This is a bottle neck in process at the moment
Note this can take some time: <br>
but we have left the step here.

#### Using trick to get unique list
https://stackoverflow.com/questions/39383557/show-distinct-column-values-in-pyspark-dataframe<br>
has to be a better and faster way however...<br>
### For brevity we can skip
as we know what our mmis list is for this case, so the getting unique list peice commented out

In [16]:
#Time check
startWorkup= datetime.now()

# Special case when we have defined our ais fetch based on ships
iterationList = get_mmsi
# below is what we normally do but it takes some time.
#iterationList = ais_data.select('mmsi').dropDuplicates().toPandas()['mmsi'].to_list() #Get our unique list of ships here!
#Feed back to user what is scale we are dealing with?
print(f"Number of mmsi  identifed in data\nIs:{len(iterationList)}")
print(f"Process takes time\nOf:{datetime.now()-startWorkup}")

Number of mmsi  identifed in data
Is:1
Process takes time
Of:0:00:00.000098

In [17]:
# debug prove we have something meaningfull here
iterationList[0]

250006549

# 5 - Define internal processing

## 5.1: define internal function for processing stopped ship event
\_result_calculator: Intenal funtion to calculate a result from stopped ship event (the_trigger)

In [18]:
def _result_calculator(the_trigger, delta_time_lower, delta_time_upper, min_valid_records, factor=2,geom_type='box'):
    '''
    Intenal funtion to calculate a result from stopped ship event (the_trigger)
    
    Parameters
    ----------
    the_trigger - list: from termination of stopped ship by either escape
        or end of time period.
    delta_time_lower - float: lower time estimate of stopped ship event
        calculated by _lower_upper_time_estimates
    delta_time_upper - float: upper time estimate of stopped ship event
        calculated by _lower_upper_time_estimates  
    min_valid_records - integer: minimum size of observations wrapped up into the_trigger for which
        it is acceptable to use this method.  This is driven by statistical imperatives in so far as
        it uses standard deviations and this requires a minimum number of observations to be valid.
    factor - integer{default:2}: used to create bounding box.  Corresponds to the number of standard deviations
        used for box creation
    geom_type - string{default:'box'} controls types of wkt returned
        'box': Returns well known text (wkt) representation of bounding box based on
            average lat/long standard deviations of observations used
        'tri-line': Creates a tri-line of three points as well known text (wkt).
            The three points of the tri line correspond to: 
            -trigger event, 
            -average co-ord, 
            -last co-ordinates in stopping event (observation prior to disarm event)
        'point': Creates a point as well known text (wkt).
            point corresponds to trigger event.
    
    
    Returns
    ----------
    tuple - (string, list, header_list)
        string contains flag as to validity of stopping event
        list contains data of stopping event
        header_list of strings for naming list down stream
    
    NOTES
    ----------
    We have expectation on schema of the trigger
                the_trigger.append(row[idx_h3])  #0
                the_trigger.append(the_mmsi) #1
                the_trigger.append(the_imo) #2
                the_trigger.append(row[idx_obs_time]) #3 trigger time
                the_trigger.append(row[idx_ais_length]) #4
                the_trigger.append(row[idx_ais_width]) #5
                the_trigger.append(row[idx_ais_vessel_type]) #6
                the_trigger.append(row[idx_ais_vessel_type_main]) #7
                
                the_trigger.append([row[idx_nav]]) #-6 [list of of navigation status]
                the_trigger.append([row[idx_cluster_time]]) #-5 [list of unix times observed]
                the_trigger.append([row[idx_lat]]) #-4 [list of lat observations]
                the_trigger.append([row[idx_lng]]) #-3 [list of lng observations]
                
                the_trigger.append(state_value) #-2
                the_trigger.append(1) #-1  number of records observed is last              
                
    We have expectation of schema of the result
                h3
                mmsi
                imo
                ais_length
                ais_width
                ais_vessel_type
                ais_vessel_type_main
                obs_time
                visit_lower
                visit_upper
                unix_trigger
                unix_average
                unix_disarm
                standard_deviation_lat
                standard_deviation_lat
                trigger_lat
                trigger_lng
                average_lat
                average_lng
                disarm_lat
                disarm_lng
                state_start
                state_end
                record_count
                status
                wkt [box|triline|point]
                wkt_avg_pt
                
                

    '''
    result = []
    
    # define header list that will can be used to convert to data frame: save someone having to do this later.
    '''header_list = ['h3_index_int','mmsi','imo','length','width','vessel_type','vessel_type_main','obs_time',
        'time_lower','time_upper','unix_trigger','avg_unix','unix_disarm','sd_lat','sd_lng',
        'trigger_lat','trigger_lng','avg_lat','avg_lng','disarm_lat','disarm_lng',
        'state_initial','state_final','obs_count','is_valid','geom_wkt']'''
    
    header_list =['h3_index_int',
                  'mmsi','imo','length','width','vessel_type','vessel_type_main',
                  'obs_time', 'time_lower','time_upper','unix_trigger','avg_unix','unix_disarm',
                  'sd_lat','sd_lng','trigger_lat','trigger_lng','avg_lat','avg_lng','disarm_lat','disarm_lng',
                  'mode_nav_status', 'obs_nav_status',
                  'state_initial','state_final','obs_count','is_valid','geom_wkt','wkt_avg_pt']
    
    
    try:
        if not (geom_type=='box' or geom_type=='tri-line' or geom_type=='point'  ):
            raise ValueError("geom_type input: only one of box|tri-line|point are acceptable values.")



        # we assume status is valid and mutate for case where it is not!
        #status = 'valid'
        
        # get trigger location and time
        trigger_lat = the_trigger[-4][0]
        trigger_lng = the_trigger[-3][0]
        unix_trigger= the_trigger[-5][0]
        
        # get average location and time
        avg_lat = cso_u.calc_list_average(the_trigger[-4])
        avg_lng = cso_u.calc_list_average(the_trigger[-3])
        avg_unix = math.floor(cso_u.calc_list_average(the_trigger[-5]))# always want an integer second. use floor
        
        # get mode of navigation status and number of observations in mode
        #print(the_trigger[-6])
        full_mode_nav_status = cso_u.calc_list_mode(the_trigger[-6],1) # get last value in mode list
        mode_nav_status = full_mode_nav_status[0] # get the mode value
        obs_nav_status = full_mode_nav_status[1] # gets the count of time this is use in this stopped ship event
        
        # get disarm location and time
        disarm_lat = the_trigger[-4][-1]
        disarm_lng = the_trigger[-3][-1]  
        unix_disarm = the_trigger[-5][-1] 
        
          
        #deal with valid stopping events, sufficent observations
        if the_trigger[-1]> min_valid_records:
            status = 'valid'

            # internal helper acting on lat/lng now safe to do standard deviation caluation
            standard_deviation_lat = cso_u.calc_list_standard_deviation(the_trigger[-4])
            standard_deviation_lng = cso_u.calc_list_standard_deviation(the_trigger[-3])

            # deal with geom and wkt value now.
            if geom_type == 'box':
                wkt = cso_u.calc_stddev_boundingbox_wkt(avg_lat,avg_lng,standard_deviation_lat,standard_deviation_lng,factor)
            elif geom_type == 'tri-line':
                wkt = cso_u.calc_tri_line_wkt(trigger_lat,trigger_lng, avg_lat, avg_lng, disarm_lat, disarm_lng)
            else:
                wkt = cso_u.calc_point_wkt(trigger_lat,trigger_lng)
                
            wkt_avg_pt = cso_u.calc_point_wkt(avg_lat,avg_lng)

        #deal with invalid stopping events, insufficent observations
        else:
            status = 'invalid'
            wkt = cso_u.calc_point_wkt(trigger_lat,trigger_lng)
            wkt_avg_pt = cso_u.calc_point_wkt(trigger_lat,trigger_lng)
            # set all non trigger inputs to 0
            standard_deviation_lat = 0 
            standard_deviation_lng = 0


        # populate result with trigger data passed in to function 
        result.append(the_trigger[0]) # h3
        result.append(the_trigger[1]) # mmsi
        result.append(the_trigger[2]) # imo
        result.append(the_trigger[4]) # ais_length
        result.append(the_trigger[5]) # ais_width
        result.append(the_trigger[6]) # ais_vessel_type
        result.append(the_trigger[7]) # ais_vessel_type_main
        result.append(the_trigger[3]) # obs_time
        
        # Now append passed in values to function
        result.append(delta_time_lower)
        result.append(delta_time_upper)        
        
        # Now append result with data derived in function
        result.append(unix_trigger)
        result.append(avg_unix)
        result.append(unix_disarm)
        result.append(standard_deviation_lat)
        result.append(standard_deviation_lng)
        result.append(trigger_lat)
        result.append(trigger_lng)
        result.append(avg_lat)
        result.append(avg_lng)
        result.append(disarm_lat)
        result.append(disarm_lng)
        
        result.append(mode_nav_status)
        result.append(obs_nav_status)
        
        result.append(the_trigger[-2][0]) # State of observation stream at start of stopping event
        result.append(the_trigger[-2][1]) # State of observation stream at end of stopping event
        result.append(the_trigger[-1]) # Number of obserations
        result.append(status)
        result.append(wkt)
        result.append(wkt_avg_pt)
        #debug print(len(header_list))
        #debug print(len(result))
        

        # check if outputs are internally consistent.
        if (len(header_list)!=len(result)):
            raise ValueError("length of internal header list must match length of intended result\n \
                             i.e len(_result_calculator[1]) != len(_result_calculator[2])")
            
        return status, result, header_list

    except Exception as e:
        print(f'Result calculation fail...')
        print(f'.....')
        print(f'Error: \n{e}\n')

## 5.2: define variables used for creating stopped ship events

In [19]:
# for Geometry Creation parameters
std_dev_factor = 1
geom_type = 'box'
geom_type = 'tri-line'

# for observation 
min_ship_observations = 20 #Min number of observations we are willing to use for a ship
min_observations = 10 # Min number of observations we are willing to use for a 'valid' stopping event

the_insufficent = [] #List for adding list of insufficent observations so we can have a metric on this.
the_nonVisits = [] #List for adding list of non visit reporting ships.
the_stopped_ship = [] #List for adding list of port visits

# tuple (the_mmsi,) # Note this is a pythonic quirk for single element tuples
set_ship = set() # set which will contain tuples as above.

# to clean up: use idx_variable for data pulled from pandas
# always going to put h3 first and cluster time 2nd in any list
idx_h3 = 0 
idx_cluster_time = 1
idx_nav = 2
idx_obs_time = 3
idx_ais_length = 4
idx_ais_width  = 5
idx_ais_vessel_type = 6
idx_ais_vessel_type_main = 7

idx_sog = 8
idx_cog = 9
idx_imo = 10

idx_goss_tonnage = 11 # don't know if we are going to use this.. but if we do this will need to move

#alway going to put lat and long as last two...
idx_lat = -2
idx_lng = -1

# used -ve indexes for the_trigger only values
idx_ref_counts= -1 #style: the number of counts will always be 2nd last in any list used
idx_ref_state = -2 #style: the state variable will always be 3rd last in any list used

#lat/long lists are used for statistical calculations of average, standard deviation and mode
idx_lng_list = -3 #style: this list of longitudes in stopping event will always be 4th last in any list used
idx_lat_list = -4 #style: this list of latitudes in stopping event will always be 5th last in any list used
idx_time_list = -5 #style: this list of unix times will be used to create average time and get first/lat
idx_nav_status_list = -6 #Style: this list of navigation status will be used to create mode of observations

In [20]:
# To allow for the possibility of sorting in reverse time set this boolean to False
time_sort_order = True
time_factor = 1 #Use in caculating time diffs, result depends on sort order
if not time_sort_order:
    time_factor = -1

# 6: Stopped Ship Event
## 6.1 We want to be able to control what gets tested
Creating test_list value to use for iteration through mmsi values.<br>
Below we are using a variable test_list which allows us to slice our iterationList for testing and debugging or production running on the full list without changing much code.

In [21]:
#test data or what we are going to shove into the 
# case: random part of list
#test_list = iterationList[20:40]

# case: some specefic cases we want to look at
#test_list = [iterationList[10],iterationList[150],iterationList[300]]

# case: production everything in iteration list.
test_list = iterationList

## 6.2: We have our data now use it.
create a subset dataframe (subset_df) of only data necessary to do the use case.<br>
For your information this may take about 20mins to run.<br>

In [22]:
subset_df = ais_data.select('mmsi',
                                   the_h3, #remember this is a hyper-parameter value!
                      "cluster_time",
                      "nav_status",
                      "dt_pos_utc",

                      "length",
                      "width",
                      "vessel_type",
                      "vessel_type_main",                      
                      
                      "sog",
                      "cog", 
                      "imo",
                      "latitude",
                      "longitude").cache()

In [23]:
# now try run time for pandas conversion.
startProcess = datetime.now()

mmsi_list_length = len(test_list) #want this to give progress report to user
mmsi_list_count = 0

# Iteration through our mmsi test list for each ship
for x in test_list:
    mmsi_list_count += 1 # update mmsi_list_count
    the_mmsi = x
    #the_mmsi = x[0]
    the_imo = -1 # we want a number so default value to use
    
    isFirst = True
    isLast = False
    
    the_trigger = []
    the_prior = []
    the_previous = []    
    
    # create a filter pandas data frame f for a given mmsi from pyspark data frame
    f = subset_df.filter(subset_df['mmsi']==the_mmsi).toPandas()
    
    # Sort it on cluster time and use this to iterate got (g) data for a given mmsi, don't need that col any more
    # This is a hang over from original process
    g = f.loc[(f['mmsi']== the_mmsi) ,
                     [the_h3, #remember this is a hyper-parameter value!
                      "cluster_time",
                      "nav_status",
                      "dt_pos_utc",

                      "length",
                      "width",
                      "vessel_type",
                      "vessel_type_main",                      
                      
                      "sog",
                      "cog", 
                      "imo",
                      "latitude",
                      "longitude"]].sort_values(by=['cluster_time'])
    observations =  len(g.index)
    
    #check we have min number of observations: if not next....Don't even entertain these cases!
    if observations <= min_ship_observations:
    
        the_insufficent.append([f"Insufficent obs:{len(g.index)}",
                                the_mmsi                     
                               ])
        
        #Giving user feedback on progress
        if mmsi_list_count % 20 == 0:
            print(f"Processed {round(mmsi_list_count/mmsi_list_length*100)}%: {mmsi_list_count} of {mmsi_list_length} mmsi ")
        elif mmsi_list_count == mmsi_list_length:
            print(f"Done! Processed: {mmsi_list_count} of {mmsi_list_length} mmsi ")        
        
        # No skip out of for loop on test_list
        continue
    else:
        count = 0 

        
    for row_index,row in g.iterrows():

        # Where is the observation in the stream of observations
        # Need to know to deal with special cases of first and last observations in stream.
        count = count+1
        if count > 1 and isFirst == True :
            isFirst = False
        if count == observations and not isLast:
            isLast = True
       
        # Create a state variable for observaion value 1,2,3
        # 1 special case first observation --> Ship was stopped initially at start of time period
        # 2 normal case mid stream neither special case of first or last observaion --> Ship stopped during time period
        # 3 special case last observation --> Ship stopped at end of time period
        state = 2
        if isFirst:
            state = 1 
        if isLast:
            state =3        
        
        #define the_current: always put co-ord pair in list at end of list...
        the_current = [
                        row[idx_h3], #0
                        row[idx_cluster_time],#1
                        row[idx_nav],#2
                        row[idx_obs_time], #3
                        row[idx_ais_length], #4
                        row[idx_ais_width], #5
                        row[idx_ais_vessel_type], #6
                        row[idx_ais_vessel_type_main], #7
                        row[idx_ais_vessel_type_main], #8
                        [row[idx_lat],row[idx_lng]] 
                      ]
        
        # imo is static variable: and may or may not exist our data.
        # only reset default value if we have imo number in our data to use.
        if not math.isnan(row[idx_imo])  and the_imo == -1:
            # Cast to integer
            the_imo = int(row[idx_imo])

        # deal with special case of first record
        if isFirst  :
            # deal with special case
            the_previous = the_current
            
        #test on speed    
        if row[idx_sog] == 0:
            
            # initilise the_trigger
            if len(the_trigger)==0:
                
                # we need to know if a ship was in port at the start and end of time period
                # initialise with current state, list with two values:
                # [state when reference started, state when reference ended]

                state_value = [state,state]
                
                #Populate the trigger with static data: use positive index for these cases
                the_trigger.append(row[idx_h3])  #0
                the_trigger.append(the_mmsi) #1
                the_trigger.append(the_imo) #2
                the_trigger.append(row[idx_obs_time]) #3
                the_trigger.append(row[idx_ais_length]) #4
                the_trigger.append(row[idx_ais_width]) #5
                the_trigger.append(row[idx_ais_vessel_type]) #6
                the_trigger.append(row[idx_ais_vessel_type_main]) #7

                # we store lists in these indexes and populate with first element of list
                # lists for nav_status, time, lat, lng for stopped ship event
                # we use negative indexing for these cases
                the_trigger.append([row[idx_nav]]) # -6 
                the_trigger.append([row[idx_cluster_time]]) #-5
                the_trigger.append([row[idx_lat]]) #-4
                the_trigger.append([row[idx_lng]]) #-3
                the_trigger.append(state_value) #-2
                the_trigger.append(1) #-1

                #Do some other clean up actions
                the_prior = the_previous
                set_ship.add((the_mmsi,)) #adding tuple to set
            else:
                if cso_p.cso_h3_adjacency_test(the_current[idx_h3],cso_p.cso_k_ring(the_trigger[idx_h3],the_k_depth)):
                    the_trigger[idx_ref_counts] += 1 # update count
                    the_trigger[idx_ref_state][1] = state # update state_value for end with current state
                    
                    # add nav_status, time, lat longs to list
                    the_trigger[idx_nav_status_list].append(row[idx_nav]) #-6
                    the_trigger[idx_time_list].append(row[idx_cluster_time]) #-5
                    the_trigger[idx_lat_list].append(row[idx_lat]) #-4
                    the_trigger[idx_lng_list].append(row[idx_lng]) #-3
                    
                else:
                    # Escape event reached, no longer within K-Ring
                    #calculate time difference for upper and lower bounds
                    t = cso_u.calc_lower_upper_time_estimates(the_prior[idx_cluster_time], 
                                                   the_trigger[-5][0], 
                                                   the_previous[idx_cluster_time],
                                                   the_current[idx_cluster_time],
                                                   time_factor)
                    delta_time_upper = t[1]
                    delta_time_lower = t[0]
                    
                    # now make a result
                    result = _result_calculator(the_trigger, delta_time_lower, delta_time_upper, 
                                                min_observations, std_dev_factor,geom_type)
                    # Append--------------------------------------
                    the_stopped_ship.append(result)
                    
                    #now flush our stack
                    del result
                    the_trigger.clear()
                    the_prior.clear()

        
        else:
            # Non zero speed cases and un-flushed trigger.
            if len(the_trigger) > 0:

                if cso_p.cso_h3_adjacency_test(the_current[idx_h3],cso_p.cso_k_ring(the_trigger[idx_h3],the_k_depth)):
                    #update the number of observations to the reference by 1 only if not the first
                    the_trigger[idx_ref_counts] += 1
                    # update state_value for end with current state
                    the_trigger[idx_ref_state][1] = state
                    
                    the_trigger[idx_nav_status_list].append(row[idx_nav]) #-6
                    the_trigger[idx_time_list].append(row[idx_cluster_time]) #-5
                    the_trigger[idx_lat_list].append(row[idx_lat]) #-4
                    the_trigger[idx_lng_list].append(row[idx_lng]) #-3
                    
                else:
                    # Escape event reached, no longer within K-Ring
                    #calculate time difference for upper and lower bounds
                    t = cso_u.calc_lower_upper_time_estimates(the_prior[idx_cluster_time], 
                                                    the_trigger[-5][0],
                                                    the_previous[idx_cluster_time], 
                                                    the_current[idx_cluster_time],
                                                    time_factor)
                    delta_time_upper = t[1]
                    delta_time_lower = t[0]

                    # now make a result
                    result = _result_calculator(the_trigger, delta_time_lower, delta_time_upper, 
                                                min_observations, std_dev_factor,geom_type)
                    
                    # Append-------------------------------------
                    the_stopped_ship.append(result)
                    
                    #now flush our stack
                    del result
                    the_trigger.clear()
                    the_prior.clear()


        #put the the_current  into the_previous so we can use it in next iteration
        the_previous  = the_current   
        
        # deal with special case of last record case where ship is in port record and unflushed stack
        if isLast and len(the_trigger) > 0:
            
            the_trigger[idx_ref_counts] += 1 # update count
            the_trigger[idx_ref_state][1] = state
            
            the_trigger[idx_nav_status_list].append(row[idx_nav]) #-6
            the_trigger[idx_time_list].append(row[idx_cluster_time]) #-5
            the_trigger[idx_lat_list].append(row[idx_lat]) #-4
            the_trigger[idx_lng_list].append(row[idx_lng]) #-3

            #calulate upper and lower time bounds - No escape so use the_current time twice
            t = cso_u.calc_lower_upper_time_estimates(the_prior[idx_cluster_time], 
                                           the_trigger[-5][0], 
                                           the_current[idx_cluster_time],
                                           the_current[idx_cluster_time], 
                                           time_factor)
            delta_time_upper = t[1]
            delta_time_lower = t[0]
 
            # now make a result
            result = _result_calculator(the_trigger, delta_time_lower, delta_time_upper, 
                                        min_observations, std_dev_factor,geom_type)

            the_stopped_ship.append(result)

            #now flush our stack
            del result
            the_trigger.clear()
            the_prior.clear()
            the_previous.clear()

            if((the_mmsi,)) not in set_ship:
                the_nonVisits.append([f"Non visiting obs:{len(g.index)}",
                                      the_mmsi])


    # We are not providing user with some feedback to show something is happening
    # Update every 20th mmsi processed, note this can be passed over by check on number of ship observations
    # Purpose is to give feedback to user and show something is happening and not hanging...
    if mmsi_list_count % 20 == 0:
        print(f"Processed {round(mmsi_list_count/mmsi_list_length*100)}%: {mmsi_list_count} of {mmsi_list_length} mmsi ")
    elif mmsi_list_count == mmsi_list_length:
        print(f"Done! Processed: {mmsi_list_count} of {mmsi_list_length} mmsi ")

/tmp/ipykernel_2884/1442447444.py:85: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  row[idx_h3], #0
/tmp/ipykernel_2884/1442447444.py:86: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  row[idx_cluster_time],#1
/tmp/ipykernel_2884/1442447444.py:87: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  row[idx_nav],#2
/tmp/ipykernel_2884/1442447444.py:88: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  row[idx_obs_time], #3
/tmp/ipykernel_2884/1442447444.py:89: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  row[idx_ais_length], #4
/tmp/ipykernel_2884/1442447444.py:90: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  row[idx_ais_width], #5
/tmp/ipykernel_2884/1442447444.py:91: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  row[idx_ais_vessel_type], #6
/tmp/ipykernel_2884/1442447444.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  row[idx_ais_vessel_type_main], #7
/tmp/ipykernel_2884/1442447444.py:93: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  row[idx_ais_vessel_type_main], #8
/tmp/ipykernel_2884/1442447444.py:94: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  [row[idx_lat],row[idx_lng]]
/tmp/ipykernel_2884/1442447444.py:99: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if not math.isnan(row[idx_imo])  and the_imo == -1:
/tmp/ipykernel_2884/1442447444.py:101: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_imo = int(row[idx_imo])
/tmp/ipykernel_2884/1442447444.py:109: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if row[idx_sog] == 0:
/tmp/ipykernel_2884/1442447444.py:121: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger.append(row[idx_h3])  #0
/tmp/ipykernel_2884/1442447444.py:124: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger.append(row[idx_obs_time]) #3
/tmp/ipykernel_2884/1442447444.py:125: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger.append(row[idx_ais_length]) #4
/tmp/ipykernel_2884/1442447444.py:126: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger.append(row[idx_ais_width]) #5
/tmp/ipykernel_2884/1442447444.py:127: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger.append(row[idx_ais_vessel_type]) #6
/tmp/ipykernel_2884/1442447444.py:128: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger.append(row[idx_ais_vessel_type_main]) #7
/tmp/ipykernel_2884/1442447444.py:133: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger.append([row[idx_nav]]) # -6
/tmp/ipykernel_2884/1442447444.py:134: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger.append([row[idx_cluster_time]]) #-5
/tmp/ipykernel_2884/1442447444.py:135: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger.append([row[idx_lat]]) #-4
/tmp/ipykernel_2884/1442447444.py:136: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger.append([row[idx_lng]]) #-3
/tmp/ipykernel_2884/1442447444.py:149: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger[idx_nav_status_list].append(row[idx_nav]) #-6
/tmp/ipykernel_2884/1442447444.py:150: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger[idx_time_list].append(row[idx_cluster_time]) #-5
/tmp/ipykernel_2884/1442447444.py:151: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger[idx_lat_list].append(row[idx_lat]) #-4
/tmp/ipykernel_2884/1442447444.py:152: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger[idx_lng_list].append(row[idx_lng]) #-3
/tmp/ipykernel_2884/1442447444.py:187: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger[idx_nav_status_list].append(row[idx_nav]) #-6
/tmp/ipykernel_2884/1442447444.py:188: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger[idx_time_list].append(row[idx_cluster_time]) #-5
/tmp/ipykernel_2884/1442447444.py:189: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger[idx_lat_list].append(row[idx_lat]) #-4
/tmp/ipykernel_2884/1442447444.py:190: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  the_trigger[idx_lng_list].append(row[idx_lng]) #-3

Done! Processed: 1 of 1 mmsi

## 6.3: Report to user done creating initial stopped ships listing

In [24]:
print(f"Completed initial stopped ships calcuation")    
print(f"Ships in domain is: MMSI's is:..{mmsi_list_length}")
print(f"Stopped Ships data: Lenght is:..{len(the_stopped_ship)}")
print(f"Insufficent data: Lenght is:....{len(the_insufficent)}")
print(f"Non vists data: Lenght is:......{len(the_nonVisits)}")

# get a run time for this process
print(f"spark2pandas process takes time\nOf:{datetime.now()-startProcess}")

Completed initial stopped ships calcuation
Ships in domain is: MMSI's is:..1
Stopped Ships data: Lenght is:..136
Insufficent data: Lenght is:....0
Non vists data: Lenght is:......0
spark2pandas process takes time
Of:0:27:10.048620

# 7 - Use stopped ship data
## Have a list of stopped ships that we now need to do stuff to.
1. Convert stopped ships list into a data frame
1. Get ships data
1. Join to ships data (on IMO inner join + remainder on mmsi inner join + no join possible (unmatched mmsi join)
1. rebuild point object for each case
1. Link to ports data via spatial join.

### 7.1 Convert list to data frame

In [25]:
# structure of stopped ship event is tupel from result calculator
# (status, result, header_list)
fieldListStoppedShip = the_stopped_ship[-1][-1]


# For demonstation only print sample data
#print(the_stopped_ship[-1][1])
#print(fieldListStoppedShip)

# now get our stopped ship ship result from tuple
new_list = []
for ss in the_stopped_ship:
    new_list.append(ss[1])

# health warning: for lists of mmsi's we may not be able to infer type so we
# are being explicit and defining and not inferring schema
# https://stackoverflow.com/questions/40517553/pyspark-valueerror-some-of-types-cannot-be-determined-after-inferring
# error risk: ValueError: Some of types cannot be determined after inferring
# Upper and lower time estimates are decimal as function rounds to 2 dp.  99999.99 hrs ≈ 11.4 years.
# Failing to implement as decimal try float.

from pyspark.sql.types import StructType, StructField, StringType, DoubleType, LongType, IntegerType, TimestampType, DecimalType

schema = StructType([ 
StructField('h3_index_int', LongType(),True),
StructField('mmsi', IntegerType(),True),
StructField('imo', IntegerType(),True), 
StructField('length',DoubleType() ,True),
StructField('width',DoubleType() ,True), 
StructField('vessel_type', StringType(), True), 
StructField('vessel_type_main', StringType(), True), 
StructField('obs_time',TimestampType() , True), 
StructField('time_lower', DoubleType(),True), 
StructField('time_upper', DoubleType(),True), 
StructField('unix_trigger', IntegerType(),True), 
StructField('avg_unix', IntegerType(),True), 
StructField('unix_disarm', IntegerType(),True), 
StructField('sd_lat',DoubleType() ,True),
StructField('sd_lng',DoubleType() ,True), 
StructField('trigger_lat',DoubleType() ,True),
StructField('trigger_lng',DoubleType() ,True), 
StructField('avg_lat',DoubleType() ,True),
StructField('avg_lng',DoubleType() ,True), 
StructField('disarm_lat',DoubleType() ,True), 
StructField('disarm_lng',DoubleType() ,True), 
StructField('mode_nav_status',  StringType(), True),
StructField('obs_nav_status', IntegerType(), True), 
StructField('state_initial', IntegerType(), True), 
StructField('state_final',  IntegerType(), True),
StructField('obs_count', IntegerType(), True), 
StructField('is_valid', StringType(), True), 
StructField('geom_wkt', StringType(), True), 
StructField('wkt_avg_pt', StringType(), True)
])
    

pd_stopped_ship = pd.DataFrame(new_list, columns=fieldListStoppedShip)
df_stopped_ship = spark.createDataFrame(pd_stopped_ship,schema=schema )
del  new_list

## 7.2 get ships data

In [26]:
# Ganti basepath lama dengan yang baru
basepath = "s3a://ais-data-142496269814/register/"
version_file = "version.csv"
ship_fact_data = "ShipData.CSV"

data2 = basepath + ship_fact_data
ships = spark.read.load(data2, format="csv", sep=",", inferSchema="true", header="true")

In [27]:
ship_data = cso_u.cso_dataframe_stripper(spark, ships,columns_shipping)
ship_data.head(1)

root
 |-- LRIMOShipNo: integer (nullable = true)
 |-- ShipName: string (nullable = true)
 |-- MaritimeMobileServiceIdentityMMSINumber: integer (nullable = true)
 |-- Tonnagesystem69convention: string (nullable = true)
 |-- GrossTonnage: integer (nullable = true)
 |-- Deadweight: integer (nullable = true)
 |-- ShiptypeLevel5: string (nullable = true)

[Row(LRIMOShipNo=7389429, ShipName='VOLANS', MaritimeMobileServiceIdentityMMSINumber=None, Tonnagesystem69convention='I', GrossTonnage=168524, Deadweight=362118, ShiptypeLevel5='Crude Oil Tanker')]

In [28]:
#Cara 4: Konversi ke Pandas (lebih rapi)
ship_data.limit(10).toPandas()  # tampilkan 10 baris dalam format tabe

,LRIMOShipNo,ShipName,MaritimeMobileServiceIdentityMMSINumber,Tonnagesystem69convention,GrossTonnage,Deadweight,ShiptypeLevel5
0,8547640,TEMEL BALIKCILIK,NaN,I,31,0,Fishing Vessel
1,8547652,TEVFIK REIS,NaN,I,9,0,Fishing Vessel
2,8547664,TEYZE OGULLARI,NaN,I,16,0,Fishing Vessel
3,8547676,TIRYAKILER,271072796.0,I,51,0,Fishing Vessel
4,8547688,TOLGA KAPTAN,271062136.0,I,67,0,Fishing Vessel
5,8547690,TONGUCLER,271072086.0,I,47,0,Fishing Vessel
6,8547705,TUFANOGLU,271062050.0,I,100,0,Fishing Vessel
7,8547717,TUNCAY REIS-1,NaN,I,14,0,Fishing Vessel
8,8547729,TUNCAY REIS-2,271072264.0,I,64,0,Fishing Vessel
9,8547731,TUNCAY SAGUN,271066005.0,I,85,0,Fish Carrier

## 7.3 Join using cso_a.cso_df_join to ship data

In [29]:
# Allow a user to refresh just what this does?
#cso_a.cso_df_join?

In [30]:
# get the Nulls on mmsi number
# NO IMO MATCH: Stopped ships  data only using stripper 
no1 = cso_u.cso_dataframe_stripper(spark,cso_a.cso_df_join(spark, 
                        df_stopped_ship, 
                        ship_data, 
                        "imo", 
                        'LRIMOShipNo',
                        join_type='LEFT' ),fieldListStoppedShip)

root
 |-- h3_index_int: long (nullable = true)
 |-- mmsi: integer (nullable = true)
 |-- imo: integer (nullable = true)
 |-- length: double (nullable = true)
 |-- width: double (nullable = true)
 |-- vessel_type: string (nullable = true)
 |-- vessel_type_main: string (nullable = true)
 |-- obs_time: timestamp (nullable = true)
 |-- time_lower: double (nullable = true)
 |-- time_upper: double (nullable = true)
 |-- unix_trigger: integer (nullable = true)
 |-- avg_unix: integer (nullable = true)
 |-- unix_disarm: integer (nullable = true)
 |-- sd_lat: double (nullable = true)
 |-- sd_lng: double (nullable = true)
 |-- trigger_lat: double (nullable = true)
 |-- trigger_lng: double (nullable = true)
 |-- avg_lat: double (nullable = true)
 |-- avg_lng: double (nullable = true)
 |-- disarm_lat: double (nullable = true)
 |-- disarm_lng: double (nullable = true)
 |-- mode_nav_status: string (nullable = true)
 |-- obs_nav_status: integer (nullable = true)
 |-- state_initial: integer (nullable = true)
 |-- state_final: integer (nullable = true)
 |-- obs_count: integer (nullable = true)
 |-- is_valid: string (nullable = true)
 |-- geom_wkt: string (nullable = true)
 |-- wkt_avg_pt: string (nullable = true)

In [31]:
no1.limit(10).toPandas()  # tampilkan 10 baris dalam format tabe

Empty DataFrame
Columns: [h3_index_int, mmsi, imo, length, width, vessel_type, vessel_type_main, obs_time, time_lower, time_upper, unix_trigger, avg_unix, unix_disarm, sd_lat, sd_lng, trigger_lat, trigger_lng, avg_lat, avg_lng, disarm_lat, disarm_lng, mode_nav_status, obs_nav_status, state_initial, state_final, obs_count, is_valid, geom_wkt, wkt_avg_pt]
Index: []

[0 rows x 29 columns]

In [32]:
imo_match =  cso_a.cso_df_join(spark, 
                        df_stopped_ship, 
                        ship_data, 
                        "imo", 
                        'LRIMOShipNo',
                        join_type='INNER' ).cache()
# Recycle no1 data frame as inner  on mmsi this time round
mmsi_match = cso_a.cso_df_join(spark, 
                        no1, 
                        ship_data, 
                        "mmsi", 
                        'MaritimeMobileServiceIdentityMMSINumber',
                        join_type='INNER' ).cache()

# Recycle no1 data frame as unmatched on mmsi this time round
no_match =  cso_a.cso_df_join(spark, 
                        no1, 
                        ship_data, 
                        "mmsi", 
                        'MaritimeMobileServiceIdentityMMSINumber',
                        join_type='LEFT').cache()

# now going to add col of data to retain how the ship data got attached to ais dat.
# https://stackoverflow.com/questions/44033037/adding-constant-value-column-to-spark-dataframe
# remember at start the line 
# import pyspark.sql.functions as F - we ll now we use it in anger.
# via
# xx.withColumn('shipSource', sf.lit('some text'))
imo_match=imo_match.withColumn('shipSource', F.lit('imo match')).cache()
mmsi_match=mmsi_match.withColumn('shipSource', F.lit('mmsi match')).cache()
no_match=no_match.withColumn('shipSource', F.lit('no match on imo or mmsi')).cache()

#imo_match.printSchema()
#mmsi_match.printSchema()
#no_match.printSchema()

#### Restack into single data frame
https://stackoverflow.com/questions/37332434/concatenate-two-pyspark-dataframes<br>
require everything to have the same schema.<br>

In [33]:
try:
    ais2ship = reduce(lambda x,y:x.union(y), [imo_match,mmsi_match,no_match])
    ais2ship.cache()
    #get list of contents of ais2ship before geom creation as we are going to want this later...
    ais2ship_fieldlist = ais2ship.columns

except Exception as e:
    print(f'Function requires pyspark.sql.dataframe.DataFrame object as inputs\nCheck x-Check schemas')
    print(f'Error: \n{e}\n')

#
#count_ais = ais_data.count()
#count_ais2ships = ais2ship.count()
#print(f'ais count = {count_ais}\nais2ships count = {count_ais2ships}')
#

## 7.4 Spatial join of ais2ship to port polygons
### Now going to use CSO_AIS functions in anger
#### cso_u.cso_wkt_load - use wkt of average point (wkt_avg_pt)
For the global use case we do not need to do this.<br>
This is where it would be done: left as space holder for now

In [34]:
type(ais2ship)

pyspark.sql.connect.dataframe.DataFrame

In [35]:
#Time check
startWorkup= datetime.now()
ais2ship_pd = ais2ship.toPandas()
print(f"spark2pandas process takes time\nOf:{datetime.now()-startWorkup}")
print(f"on ais_data_ports_nogeom")
try:
    del startWorkup
except:
    pass

spark2pandas process takes time
Of:0:00:01.508127
on ais_data_ports_nogeom

In [36]:
#FYI string that uses hyper-paramters to create name is 
output_csv

'Global_H3_int_index_10_k_3_period_20220101_to_20221231.csv'

In [37]:
# defined startScript at top of script so now use it
startWorkup= datetime.now()
checkTime = startWorkup - startScript
print(f"Runtime to here is: {checkTime}")
try:
    del startWorkup,checkTime
except:
    pass

Runtime to here is: 0:27:23.572003

# 8: Data push out
We are going to use create_download_link for this example.<br>

### 8.1 - create_download_link method
Only use this for about a month or two of data or reasonalby small outputs

In [38]:
af.create_download_link(ais2ship_pd,title=output_csv,filename=output_csv )
#af.create_download_link?

In [39]:
ais2ship_pd.head(10)

Empty DataFrame
Columns: [h3_index_int, mmsi, imo, length, width, vessel_type, vessel_type_main, obs_time, time_lower, time_upper, unix_trigger, avg_unix, unix_disarm, sd_lat, sd_lng, trigger_lat, trigger_lng, avg_lat, avg_lng, disarm_lat, disarm_lng, mode_nav_status, obs_nav_status, state_initial, state_final, obs_count, is_valid, geom_wkt, wkt_avg_pt, h3_index_int, mmsi, imo, length, width, vessel_type, vessel_type_main, obs_time, time_lower, time_upper, unix_trigger, avg_unix, unix_disarm, sd_lat, sd_lng, trigger_lat, trigger_lng, avg_lat, avg_lng, disarm_lat, disarm_lng, mode_nav_status, obs_nav_status, state_initial, state_final, obs_count, is_valid, geom_wkt, wkt_avg_pt, LRIMOShipNo, ShipName, MaritimeMobileServiceIdentityMMSINumber, Tonnagesystem69convention, GrossTonnage, Deadweight, ShiptypeLevel5, shipSource]
Index: []

[0 rows x 66 columns]

# Step Final Stop spark session!

In [40]:
mmsi_list_length

1

### Be a good data citizen

In [41]:
spark.stop()

In [42]:
# Done have a nice day!